/* auto-generated by NAPI-RS */
/* eslint-disable */
/**
 * Restores a maximized/minimized window, then moves/resizes it so its *visible*
 * frame (see `get_window_rect`) exactly matches `rect` — expanding by the
 * invisible resize border so adjacent tiled windows still sit flush, the way
 * Windows' own Snap does — and brings it to the foreground. `rect` is expected to
 * already be a valid target the caller computed (from `window/layout.ts`); this
 * function does no region math of its own. Returns whether the window was moved.
 */
export declare function applyWindowRect(hwnd: number, rect: WinRect): boolean

/**
 * Extracts the icon embedded in a PE file (.exe/.dll) at the given resource index and
 * returns it as PNG bytes, or `null` if the file has no icon at that index.
 */
export declare function extractIconPng(path: string, index: number): Buffer | null

/**
 * Renders the tile icon for a packaged (MSIX/UWP) app via the same
 * `IShellItemImageFactory` mechanism Explorer uses, addressed by its
 * AppUserModelID under the virtual `shell:AppsFolder`.
 */
export declare function extractPackagedIconPng(appId: string, size: number): Buffer | null

/**
 * The current foreground window handle, as an i64 (USER handles fit in 32 bits even
 * on 64-bit Windows). The launcher captures this just before it shows itself, so the
 * window-snap commands act on whatever the user was working in, not on the launcher.
 */
export declare function foregroundWindow(): number

/**
 * The window's current visible frame — DWM's extended frame bounds, i.e. the
 * painted pixels, not the underlying window rect (which can carry several px of
 * invisible resize border on the left/right/bottom). This is the same
 * screen-coordinate space Electron's `screen` module reports display work areas
 * in, so callers (TS `window/layout.ts` via `screen.getDisplayNearestPoint`) can
 * use it directly with no translation. Returns `null` if `hwnd` is invalid or DWM
 * can't report its frame (e.g. a custom-framed app).
 */
export declare function getWindowRect(hwnd: number): WinRect | null

/**
 * Enumerates packaged (MSIX/UWP) Start Menu apps by walking the virtual
 * `shell:AppsFolder`, replacing the `Get-StartApps` PowerShell cmdlet. Only items
 * whose AppUserModelID contains `!` (PackageFamilyName!AppId) are packaged apps;
 * classic desktop apps also show up in this folder but are already covered by the
 * `.lnk` shortcuts collected separately, so they're filtered out here.
 */
export declare function listStartApps(): Array<StartApp>

/**
 * Reads a `.lnk` shortcut's target path and icon location, replacing the
 * `WScript.Shell` COM object previously driven from PowerShell.
 */
export declare function resolveShortcut(path: string): ShortcutInfo | null

export interface ShortcutInfo {
  targetPath: string
  iconPath: string
  iconIndex: number
}

export interface StartApp {
  name: string
  appId: string
}

/**
 * Windows has no equivalent of macOS's Spaces-based fullscreen, so "Toggle
 * Fullscreen" maps to the closest native analogue: maximize the window (or
 * restore it, if already maximized). Returns whether the state changed.
 */
export declare function toggleMaximize(hwnd: number): boolean

export interface WinRect {
  x: number
  y: number
  width: number
  height: number
}
