/* auto-generated by NAPI-RS */
/* eslint-disable */
/**
 * Extracts the icon embedded in a PE file (.exe/.dll) at the given resource index and
 * returns it as PNG bytes, or `null` if the file has no icon at that index.
 */
export declare function extractIconPng(path: string, index: number): Buffer | null

/**
 * Renders the tile icon for a packaged (MSIX/UWP) app via the same
 * `IShellItemImageFactory` mechanism Explorer uses, addressed by its
 * AppUserModelID under the virtual `shell:AppsFolder`.
 */
export declare function extractPackagedIconPng(appId: string, size: number): Buffer | null

/**
 * Enumerates packaged (MSIX/UWP) Start Menu apps by walking the virtual
 * `shell:AppsFolder`, replacing the `Get-StartApps` PowerShell cmdlet. Only items
 * whose AppUserModelID contains `!` (PackageFamilyName!AppId) are packaged apps;
 * classic desktop apps also show up in this folder but are already covered by the
 * `.lnk` shortcuts collected separately, so they're filtered out here.
 */
export declare function listStartApps(): Array<StartApp>

/**
 * Reads a `.lnk` shortcut's target path and icon location, replacing the
 * `WScript.Shell` COM object previously driven from PowerShell.
 */
export declare function resolveShortcut(path: string): ShortcutInfo | null

export interface ShortcutInfo {
  targetPath: string
  iconPath: string
  iconIndex: number
}

export interface StartApp {
  name: string
  appId: string
}
