#!/usr/bin/env node
//
// `index.js`/`index.d.ts` in this package are auto-generated by `napi build`
// on a real Linux host (cross-compiling this addon's X11/XFixes dependencies
// from macOS/Windows isn't set up). Running `napi build` on a non-Linux host
// doesn't cross-compile a working binary — it either fails outright or leaves
// stale bindings behind — so this guard makes `npm install`/`npm run build` a
// safe no-op everywhere except an actual Linux host (or CI runner).

if (process.platform !== 'linux') {
  console.log(
    '[@magibar/linux] Skipping napi build: not running on Linux.\n' +
      '  Cross-compiling this addon from a non-Linux host isn\'t set up —\n' +
      '  build this package on a real Linux machine (or CI runner) instead.',
  )
  process.exit(0)
}

const { execFileSync } = require('child_process')

execFileSync('napi', ['build', '--platform', ...process.argv.slice(2)], { stdio: 'inherit' })
