/* auto-generated by NAPI-RS */
/* eslint-disable */

/**
 * Moves and resizes the focused window to `rect`. Sets size, then position, then
 * size again — some apps clamp or reflow their frame when it lands near a screen
 * edge, and re-asserting the size after the move is what makes the final result
 * stick (same workaround the AppleScript version used). Returns whether both
 * attributes were written successfully.
 */
export declare function applyWindowRect(pid: number, rect: MacRect): boolean

/**
 * The pid of the frontmost real application window, or `0` if none is found
 * (e.g. every window is a desktop element, or the list is empty). `exclude` is
 * our own pid — the launcher itself can briefly be the frontmost window right as
 * it's shown/hidden, and capturing it would mean later commands snap our own
 * window instead of whatever the user was actually working in.
 *
 * `CGWindowListCopyWindowInfo` needs no special permission and reports windows
 * front-to-back by on-screen stacking order, so the first entry whose layer is 0
 * (an ordinary app window — the Dock, menu bar, etc. use nonzero layers) and
 * whose owner isn't `exclude` is exactly "what the user was looking at."
 */
export declare function frontmostPid(exclude: number): number

/**
 * The focused window's current position and size, or `null` if unavailable
 * (no focused window, invalid pid, or Accessibility access not granted).
 */
export declare function getWindowRect(pid: number): MacRect | null

/**
 * Whether the focused window is currently in native macOS fullscreen (its own
 * Space). `false` for anything that can't be determined (no focused window,
 * permission not granted, or the window doesn't support this attribute at all —
 * `AXFullScreen` isn't part of the standard Accessibility attribute set, so a
 * missing-attribute error here just means "this app doesn't offer fullscreen,"
 * not a real failure).
 */
export declare function isFullscreen(pid: number): boolean

export interface MacRect {
  x: number
  y: number
  width: number
  height: number
}

/**
 * Toggles native macOS fullscreen on the focused window — the same effect as
 * clicking-and-holding the green traffic-light button and choosing "Enter/Exit
 * Full Screen." Not every window supports this; returns whether the write
 * succeeded.
 */
export declare function toggleFullscreen(pid: number): boolean
