/* auto-generated by NAPI-RS */
/* eslint-disable */

/** One row of the panel. Mirrors the renderer's `ActionsPanelItem`. */
export interface ActionsPanelItem {
  id: string
  title: string
  /** Rows sharing a section are grouped under a small header. */
  section?: string
  /** Keycaps, e.g. `["⇧", "⌘", "F"]`. */
  shortcut?: Array<string>
  /** SF Symbol name, e.g. `"star"`. */
  iconSfSymbol?: string
  /**
   * SF Symbol shown at the trailing edge, after any keycaps — e.g.
   * `"chevron.right"` on a row that opens a submenu.
   */
  accessorySfSymbol?: string
  danger?: boolean
}

/**
 * Moves and resizes the focused window to `rect`. Sets size, then position, then
 * size again — some apps clamp or reflow their frame when it lands near a screen
 * edge, and re-asserting the size after the move is what makes the final result
 * stick (same workaround the AppleScript version used). Returns whether both
 * attributes were written successfully.
 */
export declare function applyWindowRect(pid: number, rect: MacRect): boolean

/** Dismisses the panel if one is open (reports `{ kind: "close" }`). */
export declare function closeActionsPanel(): void

/**
 * The pid of the frontmost real application window, or `0` if none is found
 * (e.g. every window is a desktop element, or the list is empty). `exclude` is
 * our own pid — the launcher itself can briefly be the frontmost window right as
 * it's shown/hidden, and capturing it would mean later commands snap our own
 * window instead of whatever the user was actually working in.
 *
 * `CGWindowListCopyWindowInfo` needs no special permission and reports windows
 * front-to-back by on-screen stacking order, so the first entry whose layer is 0
 * (an ordinary app window — the Dock, menu bar, etc. use nonzero layers) and
 * whose owner isn't `exclude` is exactly "what the user was looking at."
 */
export declare function frontmostPid(exclude: number): number

/**
 * The focused window's current position and size, or `null` if unavailable
 * (no focused window, invalid pid, or Accessibility access not granted).
 */
export declare function getWindowRect(pid: number): MacRect | null

/**
 * Whether the focused window is currently in native macOS fullscreen (its own
 * Space). `false` for anything that can't be determined (no focused window,
 * permission not granted, or the window doesn't support this attribute at all —
 * `AXFullScreen` isn't part of the standard Accessibility attribute set, so a
 * missing-attribute error here just means "this app doesn't offer fullscreen,"
 * not a real failure).
 */
export declare function isFullscreen(pid: number): boolean

/**
 * Terminates `pid` — `SIGTERM` (a graceful "Quit") when `force` is `false`,
 * `SIGKILL` ("Force Quit") when `true`. Returns `false` if the process no
 * longer exists or the OS denies permission (not owned by this user); the
 * caller can't tell those apart from the bool alone and doesn't need to —
 * both are surfaced as the same inline error.
 */
export declare function killProcess(pid: number, force: boolean): boolean

/**
 * Every TCP port something is listening on, with the owning pid. Empty if the
 * OS refuses to enumerate (e.g. missing permission).
 */
export declare function listListeningPorts(): Array<NativePort>

/**
 * A snapshot of every currently running process's pid, name, CPU% and
 * resident memory. Cheap to call on a poll interval (a couple of times a
 * second) — the underlying refresh only re-reads `/proc`-equivalent process
 * tables, no per-call allocation of a new `System`.
 */
export declare function listProcesses(): Array<NativeProcess>

export interface MacRect {
  x: number
  y: number
  width: number
  height: number
}

/**
 * One listening TCP socket and the process that owns it. Cheap enough (a few
 * ms) to fetch alongside `list_processes()` on every poll tick.
 */
export interface NativePort {
  pid: number
  port: number
}

/**
 * One process's identity and live resource usage, as reported by the last
 * `list_processes()` refresh.
 */
export interface NativeProcess {
  pid: number
  name: string
  /**
   * Percentage of a single CPU core (0–100 per core, so a busy multi-core
   * process can exceed 100), matching Activity Monitor's own convention.
   */
  cpuUsage: number
  memoryBytes: number
  /**
   * Full path to the executable, when readable — lets the TS side resolve
   * an app icon (walking up to the enclosing `.app` bundle on macOS, since
   * the raw Mach-O binary carries no icon of its own). `None` for a process
   * whose executable path isn't readable (permission-restricted, or exited
   * between the refresh and this read).
   */
  path?: string
}

/** What the panel reports back: `kind` is `"select"` (with `id`) or `"close"`. */
export interface PanelEvent {
  kind: string
  id?: string
}

/**
 * `NSPasteboard.generalPasteboard.changeCount` — a counter AppKit increments
 * every time the general pasteboard's *content* changes (a copy, a cut, or
 * any programmatic write), and never otherwise. macOS has no pasteboard
 * "changed" notification/event at all — every clipboard-history app,
 * Raycast included, is built around polling *something*; the point of this
 * export is to make that something cheap. Reading it costs nothing (no IPC,
 * no permission prompt, no clipboard format negotiation) — a poller can
 * check this very frequently and only pay for an actual Electron
 * `clipboard.read()` call on the rare tick where it's moved.
 *
 * `generalPasteboard` is a process-wide singleton the caller doesn't own
 * (the selector isn't `alloc`/`new`/`copy`-prefixed), so it's never
 * released — same manual-reference-counting convention every other
 * Objective-C call in this codebase already assumes, just without a
 * bridging crate to enforce it for us here.
 */
export declare function pasteboardChangeCount(): number

/**
 * Shows the panel anchored to the bottom-right of `parent_view`'s window.
 *
 * `parent_view` is Electron's `BrowserWindow.getNativeWindowHandle()` (an
 * `NSView*`). `on_event` is called once: with `{ kind: "select", id }` when a
 * row is chosen, or `{ kind: "close" }` when dismissed (Esc, focus loss,
 * `closeActionsPanel`). Any panel already open is dismissed first.
 */
export declare function showActionsPanel(parentView: Buffer, title: string, items: ActionsPanelItem[], onEvent: (event: PanelEvent) => void): void

/**
 * Toggles native macOS fullscreen on the focused window — the same effect as
 * clicking-and-holding the green traffic-light button and choosing "Enter/Exit
 * Full Screen." Not every window supports this; returns whether the write
 * succeeded.
 */
export declare function toggleFullscreen(pid: number): boolean
