/* eslint-disable */
// @ts-nocheck

/**
 * Hand-written, not auto-generated by `napi build`.
 *
 * `napi build` normally produces this loader (and `index.d.ts`) by compiling
 * the addon and reading the type/binary metadata back out of the artifact —
 * but that requires a working cross-linker for `x86_64-unknown-linux-gnu`/
 * `aarch64-unknown-linux-gnu`, which this macOS development sandbox couldn't
 * install (a Homebrew bottle-verification failure blocked `zig`/`cargo-zigbuild`,
 * the usual no-Docker cross-compile path for napi-rs addons). This is a leaner
 * hand-written equivalent, covering just the two targets `package.json`'s
 * `napi.targets` actually declares — regenerate it properly with `napi build`
 * once this is built on a real Linux toolchain, and this file can be
 * overwritten with the auto-generated version at that point.
 */

const { readFileSync } = require('fs')

const isMusl = () => {
  try {
    if (readFileSync('/usr/bin/ldd', 'utf-8').includes('musl')) return true
  } catch {}
  try {
    return require('child_process').execSync('ldd --version', { encoding: 'utf8' }).includes('musl')
  } catch {
    return false
  }
}

function requireNative() {
  if (process.env.NAPI_RS_NATIVE_LIBRARY_PATH) {
    return require(process.env.NAPI_RS_NATIVE_LIBRARY_PATH)
  }
  if (process.platform !== 'linux') {
    throw new Error(`@benpocket/linux does not support platform "${process.platform}"`)
  }
  if (isMusl()) {
    throw new Error(
      '@benpocket/linux only ships glibc builds today (x86_64/aarch64-unknown-linux-gnu) — musl (e.g. Alpine) is not supported.',
    )
  }
  if (process.arch === 'x64') return require('./linux.linux-x64-gnu.node')
  if (process.arch === 'arm64') return require('./linux.linux-arm64-gnu.node')
  throw new Error(`@benpocket/linux does not support architecture "${process.arch}" on Linux`)
}

const nativeBinding = requireNative()

module.exports = nativeBinding
module.exports.activeWindow = nativeBinding.activeWindow
module.exports.applyWindowRect = nativeBinding.applyWindowRect
module.exports.getWindowRect = nativeBinding.getWindowRect
module.exports.hasXwaylandWindows = nativeBinding.hasXwaylandWindows
module.exports.toggleFullscreen = nativeBinding.toggleFullscreen
