/* hand-written — see index.js for why this isn't auto-generated by `napi build` */
/* eslint-disable */

/**
 * The active window's id, or `0` if none (or the only candidate was `exclude`
 * — the launcher's own X11 window id, so a stray capture of the launcher
 * itself is discarded rather than moved later).
 */
export declare function activeWindow(exclude: number): number

/**
 * Moves and resizes the window to `rect`. Unmaximizes first — most window
 * managers ignore a `ConfigureWindow` resize/move on an already-maximized
 * window, the same reason the mac/Windows paths restore the window before
 * repositioning it. That step is best-effort (a window that was never
 * maximized has nothing to remove, and this shouldn't block the actual move);
 * the `ConfigureWindow` call is what determines the return value.
 */
export declare function applyWindowRect(id: number, rect: LinuxRect): boolean

/**
 * The window's current position (translated to root/screen coordinates) and
 * size, or `null` if unavailable (invalid id, or the X11 connection is down).
 */
export declare function getWindowRect(id: number): LinuxRect | null

/**
 * Whether any X11/XWayland window exists at all right now — checked via
 * `_NET_CLIENT_LIST` on the root window, and `false` if the X11 connection
 * itself can't be established (e.g. a pure-Wayland session with no XWayland).
 * A window-management feature offered on a desktop with zero reachable
 * windows would just silently no-op every command, so this is used to hide
 * the feature entirely instead.
 */
export declare function hasXwaylandWindows(): boolean

export interface LinuxRect {
  x: number
  y: number
  width: number
  height: number
}

/**
 * Toggles EWMH `_NET_WM_STATE_FULLSCREEN` on the window — broadly supported
 * across X11 window managers (the same mechanism `wmctrl -b toggle,fullscreen`
 * drives).
 */
export declare function toggleFullscreen(id: number): boolean
