/* auto-generated by NAPI-RS */
/* eslint-disable */

/**
 * Handle for the background clipboard watcher `start_clipboard_watcher` starts. Dropping this
 * without calling `stop()` leaks the watcher's X11 connection and thread for the rest of the
 * process's life — callers must `stop()` it explicitly (e.g. on app quit), matching
 * `ClipboardPoller.stop()` on the TS side and `@magibar/win`'s `ClipboardWatcher`.
 */
export declare class ClipboardWatcher {
  /**
   * Wakes the watcher thread (via a self-addressed `ClientMessage`, since
   * `wait_for_event()` is otherwise blocked on the socket) and joins it.
   * Idempotent — a second call is a no-op.
   */
  stop(): void
}

/**
 * The active window's id, or `0` if none (or the only candidate was `exclude`
 * — the launcher's own X11 window id, so a stray capture of the launcher
 * itself is discarded rather than moved later).
 */
export declare function activeWindow(exclude: number): number

/**
 * Moves and resizes the window to `rect`. Unmaximizes first — most window
 * managers ignore a `ConfigureWindow` resize/move on an already-maximized
 * window, the same reason the mac/Windows paths restore the window before
 * repositioning it. That step is best-effort (a window that was never
 * maximized has nothing to remove, and this shouldn't block the actual move);
 * the `ConfigureWindow` call is what determines the return value.
 */
export declare function applyWindowRect(id: number, rect: LinuxRect): boolean

/**
 * The window's current position (translated to root/screen coordinates) and
 * size, or `null` if unavailable (invalid id, or the X11 connection is down).
 */
export declare function getWindowRect(id: number): LinuxRect | null

/**
 * Whether any X11/XWayland window exists at all right now — checked via
 * `_NET_CLIENT_LIST` on the root window, and `false` if the X11 connection
 * itself can't be established (e.g. a pure-Wayland session with no XWayland).
 * A window-management feature offered on a desktop with zero reachable
 * windows would just silently no-op every command, so this is used to hide
 * the feature entirely instead.
 */
export declare function hasXwaylandWindows(): boolean

export interface LinuxRect {
  x: number
  y: number
  width: number
  height: number
}

/**
 * Starts watching the system clipboard for changes via a true OS push notification instead of
 * polling: a background thread opens its own X11 connection, registers for `XFixes`
 * `SelectionNotify` events on the `CLIPBOARD` selection (`XFixesSelectSelectionInput` — the same
 * mechanism the `clipnotify` CLI tool is built on), and invokes `callback` with no arguments
 * once for every clipboard-ownership change. This is what lets the TS `ClipboardPoller` (see
 * `main/pasteboard-change-linux.ts`) skip its `setInterval` fallback entirely on Linux, the same
 * way `@magibar/win`'s `startClipboardWatcher` does on Windows.
 *
 * `XFixesSelectionNotify` only fires on a selection *ownership* change (a new copy), not on
 * every write within the same ownership — exactly the granularity `ClipboardPoller` wants.
 *
 * Blocks briefly waiting for the background thread to finish connecting and subscribing before
 * returning, so a failure (no X server/XWayland reachable, or the XFixes extension missing) can
 * be reported by returning a watcher whose internal window is already `0` rather than a handle
 * that silently never calls back.
 */
export declare function startClipboardWatcher(callback: ((err: Error | null) => any)): ClipboardWatcher

/**
 * Toggles EWMH `_NET_WM_STATE_FULLSCREEN` on the window — broadly supported
 * across X11 window managers (the same mechanism `wmctrl -b toggle,fullscreen`
 * drives).
 */
export declare function toggleFullscreen(id: number): boolean
