/**
 * Resolves a currency token — an ISO code, a symbol, or a name — to a 3-letter
 * ISO code, but only if that code is one we actually have a rate for
 * (`known`, from the rates store). That keeps the parser from claiming
 * "128 GB to MB" or "5 m to ft" as currency queries.
 */

/**
 * Every currency `open.er-api.com` publishes (ISO 4217 code → English name).
 * The rate store's `known` set is what actually gates conversion; this drives
 * name lookup and documents the supported set.
 */
export const CURRENCIES: Record<string, string> = {
  USD: 'US Dollar',
  AED: 'United Arab Emirates Dirham',
  AFN: 'Afghan Afghani',
  ALL: 'Albanian Lek',
  AMD: 'Armenian Dram',
  ANG: 'Netherlands Antillean Guilder',
  AOA: 'Angolan Kwanza',
  ARS: 'Argentine Peso',
  AUD: 'Australian Dollar',
  AWG: 'Aruban Florin',
  AZN: 'Azerbaijani Manat',
  BAM: 'Bosnia-Herzegovina Convertible Mark',
  BBD: 'Barbadian Dollar',
  BDT: 'Bangladeshi Taka',
  BGN: 'Bulgarian Lev',
  BHD: 'Bahraini Dinar',
  BIF: 'Burundian Franc',
  BMD: 'Bermudan Dollar',
  BND: 'Brunei Dollar',
  BOB: 'Bolivian Boliviano',
  BRL: 'Brazilian Real',
  BSD: 'Bahamian Dollar',
  BTN: 'Bhutanese Ngultrum',
  BWP: 'Botswanan Pula',
  BYN: 'Belarusian Ruble',
  BZD: 'Belize Dollar',
  CAD: 'Canadian Dollar',
  CDF: 'Congolese Franc',
  CHF: 'Swiss Franc',
  CLF: 'Chilean Unit of Account (UF)',
  CLP: 'Chilean Peso',
  CNH: 'Chinese Yuan (Offshore)',
  CNY: 'Chinese Yuan',
  COP: 'Colombian Peso',
  CRC: 'Costa Rican Colón',
  CUP: 'Cuban Peso',
  CVE: 'Cape Verdean Escudo',
  CZK: 'Czech Koruna',
  DJF: 'Djiboutian Franc',
  DKK: 'Danish Krone',
  DOP: 'Dominican Peso',
  DZD: 'Algerian Dinar',
  EGP: 'Egyptian Pound',
  ERN: 'Eritrean Nakfa',
  ETB: 'Ethiopian Birr',
  EUR: 'Euro',
  FJD: 'Fijian Dollar',
  FKP: 'Falkland Islands Pound',
  FOK: 'Faroese Króna',
  GBP: 'British Pound',
  GEL: 'Georgian Lari',
  GGP: 'Guernsey Pound',
  GHS: 'Ghanaian Cedi',
  GIP: 'Gibraltar Pound',
  GMD: 'Gambian Dalasi',
  GNF: 'Guinean Franc',
  GTQ: 'Guatemalan Quetzal',
  GYD: 'Guyanaese Dollar',
  HKD: 'Hong Kong Dollar',
  HNL: 'Honduran Lempira',
  HRK: 'Croatian Kuna',
  HTG: 'Haitian Gourde',
  HUF: 'Hungarian Forint',
  IDR: 'Indonesian Rupiah',
  ILS: 'Israeli New Shekel',
  IMP: 'Isle of Man Pound',
  INR: 'Indian Rupee',
  IQD: 'Iraqi Dinar',
  IRR: 'Iranian Rial',
  ISK: 'Icelandic Króna',
  JEP: 'Jersey Pound',
  JMD: 'Jamaican Dollar',
  JOD: 'Jordanian Dinar',
  JPY: 'Japanese Yen',
  KES: 'Kenyan Shilling',
  KGS: 'Kyrgystani Som',
  KHR: 'Cambodian Riel',
  KID: 'Kiribati Dollar',
  KMF: 'Comorian Franc',
  KRW: 'South Korean Won',
  KWD: 'Kuwaiti Dinar',
  KYD: 'Cayman Islands Dollar',
  KZT: 'Kazakhstani Tenge',
  LAK: 'Laotian Kip',
  LBP: 'Lebanese Pound',
  LKR: 'Sri Lankan Rupee',
  LRD: 'Liberian Dollar',
  LSL: 'Lesotho Loti',
  LYD: 'Libyan Dinar',
  MAD: 'Moroccan Dirham',
  MDL: 'Moldovan Leu',
  MGA: 'Malagasy Ariary',
  MKD: 'Macedonian Denar',
  MMK: 'Myanmar Kyat',
  MNT: 'Mongolian Tugrik',
  MOP: 'Macanese Pataca',
  MRU: 'Mauritanian Ouguiya',
  MUR: 'Mauritian Rupee',
  MVR: 'Maldivian Rufiyaa',
  MWK: 'Malawian Kwacha',
  MXN: 'Mexican Peso',
  MYR: 'Malaysian Ringgit',
  MZN: 'Mozambican Metical',
  NAD: 'Namibian Dollar',
  NGN: 'Nigerian Naira',
  NIO: 'Nicaraguan Córdoba',
  NOK: 'Norwegian Krone',
  NPR: 'Nepalese Rupee',
  NZD: 'New Zealand Dollar',
  OMR: 'Omani Rial',
  PAB: 'Panamanian Balboa',
  PEN: 'Peruvian Sol',
  PGK: 'Papua New Guinean Kina',
  PHP: 'Philippine Peso',
  PKR: 'Pakistani Rupee',
  PLN: 'Polish Złoty',
  PYG: 'Paraguayan Guarani',
  QAR: 'Qatari Rial',
  RON: 'Romanian Leu',
  RSD: 'Serbian Dinar',
  RUB: 'Russian Ruble',
  RWF: 'Rwandan Franc',
  SAR: 'Saudi Riyal',
  SBD: 'Solomon Islands Dollar',
  SCR: 'Seychellois Rupee',
  SDG: 'Sudanese Pound',
  SEK: 'Swedish Krona',
  SGD: 'Singapore Dollar',
  SHP: 'Saint Helena Pound',
  SLE: 'Sierra Leonean Leone',
  SLL: 'Sierra Leonean Leone (old)',
  SOS: 'Somali Shilling',
  SRD: 'Surinamese Dollar',
  SSP: 'South Sudanese Pound',
  STN: 'São Tomé and Príncipe Dobra',
  SYP: 'Syrian Pound',
  SZL: 'Swazi Lilangeni',
  THB: 'Thai Baht',
  TJS: 'Tajikistani Somoni',
  TMT: 'Turkmenistani Manat',
  TND: 'Tunisian Dinar',
  TOP: 'Tongan Paʻanga',
  TRY: 'Turkish Lira',
  TTD: 'Trinidad & Tobago Dollar',
  TVD: 'Tuvaluan Dollar',
  TWD: 'New Taiwan Dollar',
  TZS: 'Tanzanian Shilling',
  UAH: 'Ukrainian Hryvnia',
  UGX: 'Ugandan Shilling',
  UYU: 'Uruguayan Peso',
  UZS: 'Uzbekistani Som',
  VES: 'Venezuelan Bolívar',
  VND: 'Vietnamese Dong',
  VUV: 'Vanuatu Vatu',
  WST: 'Samoan Tala',
  XAF: 'Central African CFA Franc',
  XCD: 'East Caribbean Dollar',
  XCG: 'Caribbean Guilder',
  XDR: 'IMF Special Drawing Rights',
  XOF: 'West African CFA Franc',
  XPF: 'CFP Franc',
  YER: 'Yemeni Rial',
  ZAR: 'South African Rand',
  ZMW: 'Zambian Kwacha',
  ZWG: 'Zimbabwe Gold',
  ZWL: 'Zimbabwean Dollar',
}

/** Symbols. Ambiguous ones ($, ¥, kr, …) resolve to their commonest currency. */
const SYMBOLS: Record<string, string> = {
  $: 'USD',
  '£': 'GBP',
  '€': 'EUR',
  '¥': 'JPY',
  '₹': 'INR',
  '₩': 'KRW',
  '₽': 'RUB',
  '₺': 'TRY',
  '฿': 'THB',
  '₫': 'VND',
  '₱': 'PHP',
  '₪': 'ILS',
  '៛': 'KHR',
  '₦': 'NGN',
  '₲': 'PYG',
  '₴': 'UAH',
  '₡': 'CRC',
  '₵': 'GHS',
  '₸': 'KZT',
  '₼': 'AZN',
  '₾': 'GEL',
  '₿': 'BTC',
  R$: 'BRL',
  CHF: 'CHF',
  kr: 'SEK',
  zł: 'PLN',
}

/** Spoken / written nicknames and disambiguators for otherwise-ambiguous names. */
const ALIASES: Record<string, string> = {
  dollar: 'USD',
  dollars: 'USD',
  buck: 'USD',
  bucks: 'USD',
  'us dollar': 'USD',
  'us dollars': 'USD',
  euro: 'EUR',
  euros: 'EUR',
  pound: 'GBP',
  pounds: 'GBP',
  sterling: 'GBP',
  quid: 'GBP',
  yen: 'JPY',
  yuan: 'CNY',
  renminbi: 'CNY',
  rmb: 'CNY',
  rupee: 'INR',
  rupees: 'INR',
  won: 'KRW',
  ruble: 'RUB',
  rouble: 'RUB',
  franc: 'CHF',
  loonie: 'CAD',
  aussie: 'AUD',
  kiwi: 'NZD',
  peso: 'MXN',
  real: 'BRL',
  reais: 'BRL',
  lira: 'TRY',
  baht: 'THB',
  dong: 'VND',
  ringgit: 'MYR',
  rand: 'ZAR',
  zloty: 'PLN',
  krona: 'SEK',
  krone: 'NOK',
  dirham: 'AED',
  shekel: 'ILS',
  rupiah: 'IDR',
  riel: 'KHR',
  sol: 'PEN',
  kina: 'PGK',
  dobra: 'STN',
  hryvnia: 'UAH',
  forint: 'HUF',
  koruna: 'CZK',
  lev: 'BGN',
  leu: 'RON',
  shilling: 'KES',
  naira: 'NGN',
  cedi: 'GHS',
  birr: 'ETB',
  taka: 'BDT',
  dinar: 'KWD',
}

/** name (lowercased) → ISO code — full names from `CURRENCIES`, then aliases on top. */
const NAME_TO_CODE: Record<string, string> = (() => {
  const map: Record<string, string> = {}
  for (const [code, name] of Object.entries(CURRENCIES)) map[name.toLowerCase()] = code
  return Object.assign(map, ALIASES)
})()

/**
 * @param token   a raw token from the query ("usd", "$", "dollars", "euro")
 * @param known   the set of ISO codes the rates store can convert
 * @returns the ISO code, or `null` if `token` isn't a currency we can convert
 */
export function resolveCurrency(token: string, known: ReadonlySet<string>): string | null {
  const trimmed = token.trim()
  if (!trimmed) return null

  // Exact ISO code (case-insensitive).
  const upper = trimmed.toUpperCase()
  if (/^[A-Z]{3}$/.test(upper) && known.has(upper)) return upper

  // Symbol.
  const bySymbol = SYMBOLS[trimmed] ?? SYMBOLS[upper]
  if (bySymbol && known.has(bySymbol)) return bySymbol

  // Name / alias.
  const byName = NAME_TO_CODE[trimmed.toLowerCase()]
  if (byName && known.has(byName)) return byName

  return null
}

/** The single-character currency symbols, for splitting `$100` into `$` + `100`. */
export const SYMBOL_CHARS = Object.keys(SYMBOLS).filter((s) => s.length === 1)
